In [5]:
# imports
import numpy as np
import pandas as pd

In [3]:
# load data
data = pd.read_excel('database/grades.xlsx')
data

student  read_books_x1  class attendance_x2  final_grade_y
0       A              1                   50             60
1       B              2                   60             65
2       C              3                   70             72
3       D              4                   60             74
4       E              5                   80             85
5       F              1                   80             70
6       G              2                   90             78
7       H              3                   95             84
8       I              4                  100             90
9       J              5                  100             92

In [ ]:
# -----------------------------------------------
# BLOCO 2 – Montando a matriz X com bias (intercepto)
# -----------------------------------------------
# A matriz X vai conter:
# - 1ª coluna: todos os valores iguais a 1 (isso representa o bias β₀)
# - 2ª coluna: livros lidos (x₁)
# - 3ª coluna: presença nas aulas (x₂)
# Isso representa o modelo: y = β₀ + β₁*x₁ + β₂*x₂

X = np.column_stack((
    np.ones(len(data)), # bias (intercepto/valor inicial)
    data['read_books_x1'].values,
    data['class attendance_x2'].values
))

In [ ]:
# -----------------------------------------------
# BLOCO 3 – Montando o vetor Y com as respostas
# -----------------------------------------------
# O vetor Y contém apenas as notas reais de cada aluno

Y = data['final_grade_y'].values.reshape(-1, 1)

In [19]:
# -----------------------------------------------
# BLOCO 4 – Calculando os coeficientes β
# Fórmula: β = (Xᵀ * X)⁻¹ * Xᵀ * Y
# -----------------------------------------------

# 4.1 – Transposta de X (Xᵀ)
# Transpõe a matriz X, virando linhas em colunas. Necessário para multiplicação correta.
X_transposta = X.T
X_transposta

array([[  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   3.,   4.,   5.,   1.,   2.,   3.,   4.,   5.],
       [ 50.,  60.,  70.,  60.,  80.,  80.,  90.,  95., 100., 100.]])

In [20]:
# 4.2 – Multiplicação de Xᵀ * X
# Isso mede a relação entre as variáveis de entrada (livros, presença)
XtX = X_transposta @ X
XtX

array([[1.0000e+01, 3.0000e+01, 7.8500e+02],
       [3.0000e+01, 1.1000e+02, 2.4650e+03],
       [7.8500e+02, 2.4650e+03, 6.4525e+04]])

In [21]:
# 4.3 – Inversão de Xᵀ * X
# "Desembaraça" as relações para podermos resolver a equação
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 2.22312296e+00, -1.57780196e-03, -2.69858542e-02],
       [-1.57780196e-03,  6.31664853e-02, -2.39390642e-03],
       [-2.69858542e-02, -2.39390642e-03,  4.35255713e-04]])

In [23]:
# 4.4 – Multiplicação de Xᵀ * Y
# Mede a correlação entre as variáveis de entrada e a saída (nota)
XtY = X_transposta @ Y
XtY

array([[  770.],
       [ 2425.],
       [61980.]])

In [24]:
# 4.5 – Finalmente, cálculo do vetor de coeficientes β
# Esse vetor tem os valores ideais de β₀, β₁ e β₂
beta = XtX_inv @ XtY
beta

array([[35.39526659],
       [ 3.58949946],
       [ 0.39281828]])

In [ ]:
# -----------------------------------------------
# BLOCO 5 – Mostrando a equação do modelo ajustado
# -----------------------------------------------
print("Coeficientes β (bias e pesos):")
print(f"β₀ (intercepto)      = {beta[0][0]:.4f}")
print(f"β₁ (livros lidos)    = {beta[1][0]:.4f}")
print(f"β₂ (presença % aula) = {beta[2][0]:.4f}")

# Equação:
# nota_prevista = β₀ + β₁ * livros + β₂ * presença

Coeficientes β (bias e pesos):
β₀ (intercepto)      = 35.3953
β₁ (livros lidos)    = 3.5895
β₂ (presença % aula) = 0.3928


In [26]:
# Exemplo: prever a nota de um aluno que leu 3 livros e teve 85% de presença
livros = 3
presenca = 85
nota_prevista = beta[0][0] + beta[1][0]*livros + beta[2][0]*presenca
print(f"\nNota prevista para 3 livros e 85% de presença: {nota_prevista:.2f}")


Nota prevista para 3 livros e 85% de presença: 79.55
